#lokal repo
#- name: Add lokal rhel yum repository
#  yum_repository:
#    name: lokal
#    description: rhel lokal Repo
#    baseurl: http://srv9-apl-dwh1/rpmrepo
#    gpgcheck: no
#    enabled: yes
#  when: (ansible_distribution|lower == "redhat") or (ansible_distribution|lower == "centos")

#Add Subscription
#versi latest
#- name: Register user (doni.sungkono) and auto-subscribe
#  redhat_subscription:
#    state: present
#    username: doni.sungkono@techdata.com
#    password: cipar555
#    auto_attach: true

#versi2.4
- name: Register user (ds) and auto-subscribe
  redhat_subscription:
    state: present
    username: username
    password: password
    autosubscribe: true

#unregister subscription RHEL
- name: UnRegister user (ds) and auto-subscribe
  redhat_subscription:
    state: absent
    username: user
    password: password
    autosubscribe: no