<<<<<<< HEAD
#---
##- name: Ensure Hadoop Storage Configuration
#  tasks:
- name: Prof
  parted:
     device: /dev/sdb
     unit: GiB
     state: info
  register: sdb_info

- name: Remove all partitions from disk
  parted:
    device: /dev/sdb
    number: '{{ item.num }}'
    state: absent
  loop: '{{ sdb_info.partitions }}'  

- debug:
    msg: I'm so Big {{ ansible_devices.sdb.size }}

- name: Correct partitions exist on /dev/sdb
  parted:
    device: /dev/sdb
    state: present
    unit: GiB
    number: 1
    part_end: 2000GiB
  ignore_errors: True

- name: Use Item
  parted:
    device: /dev/sdb
    state: present
    unit: GiB
    number: 1
    part_start: 2000GiB
    part_end: 3700GiB


#- name: unMount up device 
#  mount:
#     path: "{{ item.dir }}"
#     state: unmounted
#  with_items:
#      - { dir: /data1 }
#      - { dir: /data2 }
#      - { dir: /data3 }
#      - { dir: /data4 }
#      - { dir: /data5 }
#      - { dir: /data6 }
#      - { dir: /data7 }
#      - { dir: /data8 }
#      - { dir: /data9 }
#      - { dir: /data10 }


- name: Create a xfs filesystem on /dev/sdN
=======
---
#- name: ansible create directory with_items example
#- file:
#      path: {{ item.dest }}
#      mode: {{item.mode}}
#      state: directory
#    with_items:
#      - { dest: '/data1', mode: '0755'}
#      - { dest: '/data2', mode: '0755'}
#      - { dest: '/data3', mode: '0755'}
#      - { dest: '/data4', mode: '0755'}
#      - { dest: '/data5', mode: '0755'}
#      - { dest: '/data6', mode: '0755'}
#      - { dest: '/data7', mode: '0755'}
#      - { dest: '/data8', mode: '0755'}

#versi 2.4
#- name: Creates directory
#  file:
#    path: "{{ item }}"
#    state: directory
#  with_items:
#  - /zk
#  - /nn
#  - /jn

- name: unMount up device 
  mount:
    path: "{{ item.dir }}"
    state: unmounted
  with_items:
    - { dir: /zk }
    - { dir: /nn }
    - { dir: /jn }
    - { dir: /kudu/data }
    - { dir: /kudu/wal }

- name: Create a xfs filesystem on /dev/vdN
>>>>>>> 419dbf1ae5eacd240f3e7c42580e6b8167c298a3
  filesystem:
    fstype: xfs
    force: yes
    dev: "{{ item }}"
  with_items:
<<<<<<< HEAD
    - /dev/sdb1
    - /dev/sdb2
#    - /dev/sdb
#    - /dev/sdc
#    - /dev/sdd
#    - /dev/sde
#    - /dev/sdf
#    - /dev/sdg
#    - /dev/sdh
#    - /dev/sdi
    
=======
    - /dev/sdb
    - /dev/sdc
    - /dev/sdd
    - /dev/sde
    - /dev/sdf
  
>>>>>>> 419dbf1ae5eacd240f3e7c42580e6b8167c298a3
- name: Mount up device 
  mount:
    path: "{{ item.dir }}"
    src: "{{ item.disk }}"
    fstype: xfs
    opts: defaults,noatime
    state: mounted
  with_items:
<<<<<<< HEAD
    - { dir: /hadoop/data1, disk: /dev/sdb1 }
    - { dir: /hdlog, disk: /dev/sdb2 }
#    - { dir: /data1, disk: /dev/sdb }
#    - { dir: /data2, disk: /dev/sdc }
#    - { dir: /data3, disk: /dev/sdd }
#    - { dir: /data4, disk: /dev/sde }
#    - { dir: /data5, disk: /dev/sdf }
#    - { dir: /data6, disk: /dev/sdg }
#    - { dir: /data7, disk: /dev/sdh }
#    - { dir: /data8, disk: /dev/sdi }
=======
    - { dir: /nn, disk: /dev/sdb }
    - { dir: /kudu/data, disk: /dev/sdc }
    - { dir: /kudu/wal, disk: /dev/sdd }
    - { dir: /zk, disk: /dev/sde }
    - { dir: /jn, disk: /dev/sdf }
>>>>>>> 419dbf1ae5eacd240f3e7c42580e6b8167c298a3
