---

- name: Install MariaDB packages
  yum: name={{ item }} state=installed
  with_items:
    - mariadb-server
    - MySQL-python

- name: Start MariaDB Service
  service: name=mariadb state=started enabled=yes

- include: mysql_secure_installation.yml
- include: databases.yml


