#bikin user
#cara create hash password via ansible
#https://docs.ansible.com/ansible/latest/reference_appendices/faq.html#how-do-i-generate-encrypted-passwords-for-the-user-module
#ansible all -i localhost, -m debug -a "msg={{ 'mypwdtd' | password_hash('sha512', 'wahyubudiman') }}"
#end password hash

<<<<<<< HEAD
- name: Add group "pentaho" 
  group:
    name: pentaho
    state: present

#- name: Add group "dev" 
#  group:
#    name: dev
#    state: present



#- name: Create a login user
#  user:
#   name: admin
#   password: '$6$$D5l1/8.Dpt.RanlHgiRwg0lVqivqp2JR1JFNo/Dt2LBkIoNY85f56E/SHIhbTmuTni.rGzqJE1RtWTFUMpX///'
#   group: admin
#   state: present
#   shell: /bin/bash       # Defaults to /bin/bash
#   system: no             # Defaults to no
#   createhome: yes        # Defaults to yes
#   home: /home/admin  # Defaults to /home/<username>

#- name: Create a login user
#  user:
#   name: dev
#   password: '$6$$.E7ilWqyZxbLK.PeVSc6cyw7NSimIlme26B7GnNjlV2absXWoGIrFTANGl68y/Q/k7ecw3PMC8MhTrkH4MBsT.'
#   group: dev
#   state: present
#   shell: /bin/bash       # Defaults to /bin/bash
#   system: no             # Defaults to no
#   createhome: yes        # Defaults to yes
#   home: /home/dev  # Defaults to /home/<username>


#pentaho
#pass-nya = pentaho2019
#
- name: Create a login user
  user:
   name: pentaho
   password: '$6$$2/Kih3216HLVEwfpOu1KJaiyjAaTZWcEyEtVXiPSccaqLv38HdDtt0J0O.n77K34JMUA/lEJhCc.wllPYI9qn0'
   group: pentaho
#=======
- name: Add group "admin" 
  group:
    name: admin
    state: present

- name: Add group "dev" 
  group:
    name: dev
    state: present

- name: Create a login user
  user:
   name: admin
   password: '$6$$D5l1/8.Dpt.RanlHgiRwg0lVqivqp2JR1JFNo/Dt2LBkIoNY85f56E/SHIhbTmuTni.rGzqJE1RtWTFUMpX///'
   group: admin
   state: present
   shell: /bin/bash       # Defaults to /bin/bash
   system: no             # Defaults to no
   createhome: yes        # Defaults to yes
   home: /home/admin  # Defaults to /home/<username>

- name: Create a login user
  user:
   name: dev
   password: '$6$$.E7ilWqyZxbLK.PeVSc6cyw7NSimIlme26B7GnNjlV2absXWoGIrFTANGl68y/Q/k7ecw3PMC8MhTrkH4MBsT.'
   group: dev
#>>>>>>> 419dbf1ae5eacd240f3e7c42580e6b8167c298a3
   state: present
   shell: /bin/bash       # Defaults to /bin/bash
   system: no             # Defaults to no
   createhome: yes        # Defaults to yes
#<<<<<<< HEAD
   home: /home/pentaho  # Defaults to /home/<username>
#=======
   home: /home/dev  # Defaults to /home/<username>

#>>>>>>> 419dbf1ae5eacd240f3e7c42580e6b8167c298a3
