---
# Disable SELinux
- selinux:
    state: disabled

- name: Stop Firewalld Service
  service: 
   name=firewalld 
   state=stopped 
   enabled=no

#name: create directory
- file:
   path: /usr/share/java
   state: directory
   mode: 0755

#- name: install the latest version of NTP
#  yum:
#    name: ntp
#    state: latest

#- name: Copy configuration file NTP
#  template: src=ntp.conf.j2 dest=/etc/ntp.conf

#- name: enable NTP
#  service: name=ntpd state=started enabled=yes

- name: Copy configuration file hosts
  template: src=hosts.conf.j2 dest=/etc/hosts

# Set vm.swappiness to 5 in /etc/sysctl.conf
- sysctl:
    name: vm.swappiness
    value: 1
    state: present

- name: Disable Transparant Huge Page
  template: src=rc.local.j2 dest=/etc/rc.d/rc.local mode=0755

- name: Stop Tuned Service
  service:
   name=tuned
   state=stopped
   enabled=no

#Pre package
- name: Install Prereq Package
  yum: name={{ item }} state=latest update_cache=yes
  with_items:
    - MySQL-python
    - keyutils-libs-devel
    - krb5-devel
    - libcom_err-devel
    - libselinux-devel
    - libsepol-devel
    - libverto-devel
    - m4
    - mod_ssl
    - openssl-devel
    - patch
    - pcre-devel
    - postgresql-libs
    - python-psycopg2
    - redhat-lsb-core
    - redhat-lsb-submod-security
    - spax
    - zlib-devel
    - e2fsprogs
    - e2fsprogs-libs
    - libcom_err
    - libss
    - openssl
    - openssl-libs
    - unzip
