#---
- name: Add Cloudera Manager yum repository
  yum_repository:
    name: cloudera-manager
    description: Cloudera Manager
    baseurl: https://archive.cloudera.com/cm6/6.3.1/redhat7/yum/
    gpgkey: https://archive.cloudera.com/cm6/6.3.1/redhat7/yum/RPM-GPG-KEY-cloudera
    gpgcheck: yes
    enabled: yes
  when: (ansible_distribution|lower == "redhat") or (ansible_distribution|lower == "centos")
