<<<<<<< HEAD
#---
#- name: Ensure Kafka Storage Configuration
#  tasks:
- name: Prof
  parted:
     device: /dev/sda
     unit: GiB
     state: info
  register: sda_info

#- debug:
#    msg: I'm so Big {{ ansible_devices.vdb.size }}

- name: Correct partitions exist on /dev/sda
  parted:
    device: /dev/sda
    state: present
    unit: GiB
    number: 1
    part_end: 2000GiB
  ignore_errors: True

#- debug:
#    msg:

- name: Use Item
  parted:
    device: /dev/sda
    state: present
    unit: GiB
    number: 2
    part_start: 2000GiB
    part_end: 3700GiB


#- name: unMount up device 
#  mount:
#     path: "{{ item.dir }}"
#     state: unmounted
#  with_items:
=======
---
#- name: ansible create directory with_items example
#- file:
#      path: {{ item.dest }}
#      mode: {{item.mode}}
#      state: directory
#    with_items:
#      - { dest: '/data1', mode: '0755'}
#      - { dest: '/data2', mode: '0755'}
#      - { dest: '/data3', mode: '0755'}
#      - { dest: '/data4', mode: '0755'}
#      - { dest: '/data5', mode: '0755'}
#      - { dest: '/data6', mode: '0755'}
#      - { dest: '/data7', mode: '0755'}
#      - { dest: '/data8', mode: '0755'}

#versi 2.4
#- name: Creates directory
#  file:
#    path: "{{ item }}"
#    state: directory
#  with_items:
#  - /data1
#  - /data2
#  - /data3
#  - /data4
#  - /data5
#  - /data6
#  - /data7
#  - /data8
#  - /data9
#  - /data10

#- name: unMount up device 
#    mount:
#      path: "{{ item.dir }}"
#      state: unmounted
#    with_items:
>>>>>>> 419dbf1ae5eacd240f3e7c42580e6b8167c298a3
#      - { dir: /data1 }
#      - { dir: /data2 }
#      - { dir: /data3 }
#      - { dir: /data4 }
#      - { dir: /data5 }
#      - { dir: /data6 }
#      - { dir: /data7 }
#      - { dir: /data8 }
#      - { dir: /data9 }
#      - { dir: /data10 }


- name: Create a xfs filesystem on /dev/sdN
  filesystem:
    fstype: xfs
    force: yes
    dev: "{{ item }}"
  with_items:
<<<<<<< HEAD
    - /dev/sda1
    - /dev/sda2
#    - /dev/sdb
#    - /dev/sdc
#    - /dev/sdd
#    - /dev/sde
#    - /dev/sdf
#    - /dev/sdg
#    - /dev/sdh
#    - /dev/sdi
=======
    - /dev/sdb
    - /dev/sdc
    - /dev/sdd
    - /dev/sde
    - /dev/sdf
    - /dev/sdg
    - /dev/sdh
    - /dev/sdi
>>>>>>> 419dbf1ae5eacd240f3e7c42580e6b8167c298a3
    
- name: Mount up device 
  mount:
    path: "{{ item.dir }}"
    src: "{{ item.disk }}"
    fstype: xfs
    opts: defaults,noatime
    state: mounted
  with_items:
<<<<<<< HEAD
    - { dir: /kafka_topics, disk: /dev/sda1 }
    - { dir: /hdlog, disk: /dev/sda2 }
#    - { dir: /data1, disk: /dev/sdb }
#    - { dir: /data2, disk: /dev/sdc }
#    - { dir: /data3, disk: /dev/sdd }
#    - { dir: /data4, disk: /dev/sde }
#    - { dir: /data5, disk: /dev/sdf }
#    - { dir: /data6, disk: /dev/sdg }
#    - { dir: /data7, disk: /dev/sdh }
#    - { dir: /data8, disk: /dev/sdi }
=======
    - { dir: /data1, disk: /dev/sdb }
    - { dir: /data2, disk: /dev/sdc }
    - { dir: /data3, disk: /dev/sdd }
    - { dir: /data4, disk: /dev/sde }
    - { dir: /data5, disk: /dev/sdf }
    - { dir: /data6, disk: /dev/sdg }
    - { dir: /data7, disk: /dev/sdh }
    - { dir: /data8, disk: /dev/sdi }
>>>>>>> 419dbf1ae5eacd240f3e7c42580e6b8167c298a3
